[package]
name = "wm"
version = "0.1.0"
edition = "2021"
authors = ["storycraft <storycraft@pancake.sh>"]

[dependencies]
parking_lot = "0.12.1"
winit = "0.28.6"
async-task = "4.4.0"
scopeguard = "1.2.0"
futures-lite = "1.13.0"
scoped-tls-hkt = "0.1.2"
pin-project = "1.1.3"
futures-intrusive = "0.5.0"
instant = "0.1.12"
flume = "0.10.14"
pin-list = "0.1.0"
higher-kinded-types = "0.1.1"
